<?php

$mail_domain		= "gksend002.com";
$mail_domain_type	= "virtual";    //default or vitrual
$list_host		= $mail_domain;
$list_vpopmail          = "/home/vpopmail/domains";
$list_directory         = $list_vpopmail."/".$list_host;

$InnerWebHost		= "127.0.0.1";
$OutWebHost		= "edm.gksend002.com";
$OutWebHost_Port	= "";

$mysql_program		= "/usr/local/mysql/bin/mysql";
$mysqldata_dir		= "/usr/local/mysql/data";
$mysql_user		= "root";
$mysql_pwd		= "qazwsx";
$multidomain = 99;   
?>
